// Marvish Chandra
// 2022 Schedule

val lakersSchedule = i match
  case 0 => "Tuesday"
  case 1 => "Thursday"
  case 2 => "Sunday"
  case 3 => "Wednesday"
  case 4 => "Friday"
  case 5 => "Sunday"
  case 6 => "Wedneday"
  case 7 => "Friday"
  case 8 => "Sunday"
  case 9 => "Monday"
  case 10 => "Wednesday"
  case 11 => "Friday"
  case 12 => "Sunday"
  case 13 => "Friday"
  case 14 => "Sunday"
  case 15 => "Tuesday"
  case 16 => "Friday"
  case 17 => "Saturday"
  case 18 => "Monday"
  case 19 => "Wednesday"
  case 20 => "Friday"
  case 21 => "Sunday"
  case 22 => "Tuesday"
  case 23 => "Wednesday"
  case 24 => "Friday"
  case 25 => "Sunday"
  case 26 => "Tuesday"
  case 27 => "Friday"
  case 28 => "Sunday"
  case 29 => "Monday"
  case 30 => "Wednesday"
  case 31 => "Friday"
  case 32 => "Sunday"
  case 33 => "Tuesday"
  case 34 => "Wednesday"
  case 35 => "Friday"

val clippersSchedule = i match
  case 0 => "Thursday"
  case 1 => "Saturday"
  case 2 => "Sunday"
  case 3 => "Tuesday"
  case 4 => "Thursday"
  case 5 => "Sunday"
  case 6 => "Monday"
  case 7 => "Wednesday"
  case 8 => "Friday"
  case 9 => "Sunday"
  case 10 => "Monday"
  case 11 => "Wednesday"
  case 12 => "Saturday"
  case 13 => "Monday"
  case 14 => "Tuesday"
  case 15 => "Thursday"
  case 16 => "Saturday"
  case 17 => "Monday"
  case 18 => "Wednesday"
  case 19 => "Friday"
  case 20 => "Sunday"
  case 21 => "Tuesday"
  case 22 => "Wednesday"
  case 23 => "Saturday"
  case 24 => "Monday"
  case 25 => "Wednesday"
  case 26 => "Thursday"
  case 27 => "Saturday"
  case 28 => "Monday"
  case 29 => "Wednesday"
  case 30 => "Thursday"
  case 31 => "Saturday"
  case 32 => "Wednesday"
  case 33 => "Friday"
  case 34 => "Monday"
  case 35 => "Tuesday"
  case 36 => "Thursday"
  case 37 => "Saturday"

  
  
  
